added a post
devbae/devbae-blog pull request #42
Opened 2020-08-30 09:58 UTC by ridhiratan

## Type of PR

- [ ] Blog/Article
- [ ] Feature/Enhancement
- [ ] Bug Fix

## Description

Describe the changes made and why they were made instead of how they were made. List any dependencies that are required for this change.

## Related issues and discussion

#{Issue Number}

## Screenshots, if any

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `devbae-blog/.github/CONTRIBUTING.md`.

2020-09-02 07:46 UTC, aashish-ak requested changes

2020-09-02 07:46 UTC, aashish-ak commented on _data/authors.yml
> +      url: "https://www.instagram.com/ridhi_2719/"
Add end of file newline.

2020-09-02 07:46 UTC, aashish-ak commented on _posts/2020-08-30-blockchain.md
> +
Keep only one end of line. Remove the extra ones.

2020-09-02 17:46 UTC, aashish-ak requested changes

2020-09-02 17:46 UTC, aashish-ak commented on _data/authors.yml
> +
Remove this extra line.

2020-09-02 17:46 UTC, aashish-ak commented on _data/authors.yml
>  shreyasbapat:
Add a new line.

2020-09-02 18:16 UTC, aashish-ak commented
@aroralakshya This blog is now looking fine, please give it a quick read and point out any discrepancies or errors you might find in the content, the design errors have been eradicated, now just the content needs to be reviewed once. Let me know if it's fine, will merger it. Also, good work @ridhiratan on this one, loved it, quick response to changes asked from you were cherry on the cake, will complete this review and will try to publish this blog by this weekend :)

2020-09-02 18:16 UTC, aashish-ak approved these changes

2020-09-05 11:16 UTC, aroralakshya reviewed
You have used some image from other sources. Can you write those sources below those images.

2020-09-05 12:28 UTC, ridhiratan commented
> You have used some image from other sources. Can you write those sources below those images.

I picked them up from google, no specific site..... Should I directly mention the source as google?

2020-09-05 12:55 UTC, ridhiratan commented
> You have used some image from other sources. Can you write those sources below those images.

Do check once, if what I have done is correct way of citing.

2020-09-19 08:54 UTC, aashish-ak commented
Hi @ridhiratan , There's been a confusion between me and Lakshay regarding the citing of sources, as you're directly using the original links for the images, there's no need to cite the sources as the image itself is the source. So please remove the all the sources and we'll immediately publish the blog :)
Also very sorry for the delay in merging, we assure you this won't happen in future.

2020-09-19 09:02 UTC, merged